### ISSUE TITLE
what are the best settings for minimizing lag for crack pack?

### ISSUE THREAD

**Issue by imransufi12** [sciguyryan/TheCrackPack#1012]

**Comment by evknucklehead** [comment]
It all depends on where the lag is coming from. If the lag is caused by memory issues (either not enough or too much allocated), changing your RAM allocation will help. If it's caused by a slower video card, turning down various settings, such as Render Distance and Mip Map settings, as well as reducing the size of the window, will help more. Using the optional, but highly recommended, mod FastCraft will help in many situations regarding rendering.

There are some circumstances that will also generate lag, such as excess particles or too many entities (regular and tile entities). Reducing the number of these loaded at any given time will help considerably.

If you're running a server, make sure your upstream rate can handle it. Many home internet connections have a much higher downstream rate than their upstream rate. For example, my net connection is about 12Mbit downstream, but only about 0.8Mbit Upstream. This means I can only reliably host one or two other players if I run a server from here.
