### ISSUE TITLE
Sky factory 2

### ISSUE THREAD

**Issue by antanas1452** [sciguyryan/TheCrackPack#746]
when i click on play stuff starts to load minecraft opens and then minecraft closes and the laucher just starts to check for updates

http://paste.atlauncher.com/view/ffae566e

**Comment by jberkers42** [comment]
Two things:

1. You need to use 64-bit java on a 64-bit system to play these kinds of packs.  Since you are running Windows 7, you can rebuild your machine to a 64-bit operating system, but it will require a complete re-install.  There is no 'upgrade' available.
2. This is the issue tracker for The Crack Pack rather than Sky Factory 2

**Comment by antanas1452** [comment]
so there is no chance that i will play sky factory 2 unless i will reinstal my windows?

**Comment by jberkers42** [comment]
Correct.  32-bit Java has a 1Gb memory limitation, while most mod packs require anywhere from 1.5G to  4G to run.

**Comment by antanas1452** [comment]
god dammit
