### ISSUE TITLE
New Sever Crashing on join

### ISSUE THREAD

**Issue by Sloeberry** [sciguyryan/TheCrackPack#766]
http://paste.atlauncher.com/view/523470de

**Comment by evknucklehead** [comment]
It looks to me like the server you're trying to connect to is either running a different version of the pack, doesn't have some of the optional mods installed, or is being launched incorrectly (by launching via Minecraft.jar instead of the Forge jar file.)

Confirm which version of the pack is being run and which optional mods are installed. Install a new instance of the pack with those settings. If you're still having the same problem, contact the server operator and let them know to run the server from the Forge jar instead of Minecraft.jar

PS: I would have replied sooner, but I was having trouble pulling up the page on ATLauncher's site.

**Comment by Sloeberry** [comment]
It was different mods on server and client 
THANKS :+1:
