### ISSUE TITLE
Launcher freezes, Game doesn't start

### ISSUE THREAD

**Issue by Nyck21** [sciguyryan/TheCrackPack#814]
Got the right java version, reinstalled crackpack two times, but everytime I launch the game, it freezes at"Initializing" 
My Log: http://pastebin.com/hTB8XKSM

**Comment by evknucklehead** [comment]
It's not frozen. It just takes a while to load the game. On my system, it takes somewhere between 3.5-5 minutes to load completely. There is a lot of stuff to load into the game (over 180 mod components) so it will take far longer than vanilla Minecraft.

**Comment by Nyck21** [comment]
I have to reopen this issue, because it worked ONE time, but then it stopped working again. The one time it worked it said something with the access token before the game opened. Now, I waited for like 20 minutes, but it didn't do anything.

**Comment by evknucklehead** [comment]
Bump up your maximum memory allocation to 4GB to see if that helps. It looks like you have 8GB total memory so you should be able to handle it without the side effects of going higher than that.

The bit about the access token is just the launcher checking with Mojang to see if it can log you in without sending your full login info first. If it finds that the token has expired or is otherwise no good, it will get a new one from Mojang by sending the login info.

**Comment by Nyck21** [comment]
Thank you so much for your help!! It works now :))
