### ISSUE TITLE
Closing of Minecraft upon loading of Server

### ISSUE THREAD

**Issue by Psykout** [sciguyryan/TheCrackPack#830]
It was working perfectly.

Host of server had this appear in his console:
(He has Swedish version so he had to translate) Existing connection already exists, forced to close to remove control computers. But I don't believe is correct.

So I did indeed join, before then instantly leaving.

The last action I did was right click a blood-altar thing with a decent crossbow (by accident) then attempt to quickly pick it up, the crash report suggests weaponry/crossbow loading failure or something. Now whenever I load the server, Minecraft instantly closes and I'm left at the ATLauncher.

Here is the crash report paste:
http://paste.atlauncher.com/view/9365cf77

I am sorry if I am vague, if the crash-report.txt is also needed I can copy and pastebin it. I have also updated my Java (from 7 u51 to 8..whatever) and reinstalled TheCrackPack in attempt to solve the issue.
I have all required and optional mods chosen apart from the JourneyMap (Zen is chosen instead)

**Comment by evknucklehead** [comment]
You've likely run into a bug with ExtraTiC, the mod that adds materials from other mods into Tinkers' Construct. The latest version of Tinkers' Construct changed the way certain aspects of the materials are handled, but ExtraTiC hasn't been updated to accommodate those changes. 

You'll need to have your server operator go into the server's player files and delete the crossbow and any bolts made from non-Vanilla or Tinkers' Construct/Mechworks/Steelworks materials from your inventory.

Until ExtraTiC is updated, you'll need to avoid using any of the affected materials in ranged weapons. The materials are fine for use in swords and tools, since those don't seem to be affected by this bug.

**Comment by Psykout** [comment]
Thank you for the insight. We did essentially that, but manually.
Because I existed in the server for a few seconds, they killed me in this time (thus removing it from my inventory). I then re-logged and it worked.
