### ISSUE TITLE
Failure To Launch Crackpack

### ISSUE THREAD

**Issue by IncineratedLlama** [sciguyryan/TheCrackPack#866]
I tried to launch an instance of the Crackpack (1.5.1) that I have used many times before, and it failed. The console says that it finds updates, but then receives incorrect data from them and the download fails. I have tried launching the most recent version of the pack, and it worked, though initially it said that the same packs.json download failed. I also attempted downloading a new instance of the same pack, re-downloading the exe file of the launcher and replacing it, creating an entirely new folder with a new launcher exe file, and restarting my computer. None of these worked.

Here is the log: http://paste.atlauncher.com/view/ee3123d3
The log shows me starting the launcher, and attempting to start the instance once. 

Here's another log in which I messed around with it a little, tried to launch it two or three times: http://paste.atlauncher.com/view/9695e5d3

**Comment by IncineratedLlama** [comment]
Also, I asked a friend of mine to try launching the same thing on his computer, and for him, it worked just fine.

**Comment by evknucklehead** [comment]
The updates thing is referring to the launcher itself, not the pack. They had been having issues with the packs.json file's fingerprint not getting updated when the file was updated, causing the incorrect data errors. They have since fixed that particular problem, at least for the time being.

Did you recently update to Java 8? Forge for 1.6.4 is notorious for having issues with Java 8. You can safely install Java 7 alongside Java 8, and the launcher will let you choose to use it for launching Minecraft.

**Comment by IncineratedLlama** [comment]
Thanks a ton! It's been a while since I checked here, but that makes sense.
