### ISSUE TITLE
state engine was in incorrect state

### ISSUE THREAD

**Issue by murderlot** [sciguyryan/TheCrackPack#970]
http://www.pastebin.ca/2995711

server crashes everytime i load, it's not the eula i have that on true, i'm pretty sure it's the world file as creating a new world works fine, and the backup works fine (although backup is a month old, i don't back up as often as i should, silly me), i have also tried removeErroringTileEntities=true and removeErroringEntities=true in forge.cfg, no luck there, so if anyone knows what it is that is causing the server to stop please let me know.

Thank you
Murderlot.

**Comment by evknucklehead** [comment]
Yeah, something in the world save is borked. This particular error is not caused by broken entities, which is why setting those two flags didn't help. Somehow the compression header in one of the files got screwed up, which means restoring a backup is about the only way to get back in.

Perhaps from now on you'll do more frequent backups...

**Comment by murderlot** [comment]
Ah that's unfortunate, Well hopefully i've learned my lesson now. Thank you for letting me know :+1:
