### ISSUE TITLE
How to remove glitched armor?

### ISSUE THREAD

**Issue by Steveloco1** [sciguyryan/TheCrackPack#972]
Hello, my friend tried to infuse dispel onto his leggings and the armor automatically logged him out. He hasn't been able to log in ever since but I am still able to get on and play...What can I do to remove the glitched armor that he is wearing so he can play again?

**Comment by evknucklehead** [comment]
The server operator needs to remove the armor from his inventory using either an inventory editing program or NBT Explorer. 

Alternatively, you can have a bunch of guys around where he appears attack him in the time between him appearing in game and the time he gets lagged out due to the error. Just make sure nobody picks up the armor from the gravestone that will be dropped. This won't work if KeepInventory is turned on, though.

**Comment by Steveloco1** [comment]
NBT Explorer did the trick and it worked perfectly thanks for the help:)
